
from numpy import *

# load the data
def load_data():
    # load data and split the match up attribute 
    data = matrix(genfromtxt('2015_2016 FORMER.csv', dtype = None , delimiter=','))
    attri = []
    for row in range(0,data.shape[0]):
    	attri.append(data[row,1].split())
    data = data.tolist()
    return data,attri

# combine two teams stats at the same match in one row
def combine_data(data,match_up):
	new_data = []
	for row_1 in range(1,len(data)): 
		new_row = []
		for row_2 in range(row_1,len(data)):
			if match_up[row_1][0] == match_up[row_2][2] and data[row_1][2] == data[row_2][2]:
				new_row.append(data[row_1][2:])
				new_row.extend(data[row_2][4:])	
		if new_row:
			new_data.append(new_row)
 	return new_data

def main():
	data,match_up = load_data()
	new_data = combine_data(data,match_up)
	print new_data
	
	# savetxt(
 #    '2015-2016.csv',           # file name
 #    new_data,                # array to save
 #    fmt='%.2f',             # formatting, 2 digits in this case
 #    delimiter=',',          # column delimiter
 #    newline='\n',           # new line character
 #    footer='end of file',   # file footer
 #    comments='# ',          # character to use for comments
 #    header='Data generated by numpy')      # file header

main()






